### ISSUE TITLE
Use the same tab size

### ISSUE THREAD

**Issue by niesmo** [niesmo/childcare#36]
we decided to use the same tab size across all of our editors so when someone edits your code, their IDE wouldnt change the tab sizes and the commit would look like there is a lot of changes where there actually is very minimal changes

**Tab size: 2**
**IDE should use spaces for tabs**

**Comment by SLMassari** [comment]
I made the change, I'm not sure if it's retroactive, but going forward, any tabs will be 2 spaces.
