### ISSUE TITLE
Dont actually create a user for the system, just mark the action items

### ISSUE THREAD

**Issue by niesmo** [niesmo/childcare#38]
I think another way to approach this is to simply mark the action item so that you can find out whether the action item is a system kind or not.

If you create another user, on each row, you have to get the user and check if its admin, which is a whole a lot of queries that are not absolutely necessary.

**Comment by SLMassari** [comment]
Should I just give each action item a boolean like IsSystemMessage and make createdBy an optional element?

**Comment by niesmo** [comment]
That is a good idea.
Or also instead of making the created by field optional, you could give that field a preset value. You could set that value in the settings file so that it could be changed easier and is not hard coded
