### ISSUE TITLE
dont use html markup for styling, use CSS

### ISSUE THREAD

**Issue by niesmo** [niesmo/childcare#39]
using html mark up for styling is a less maintainable way of developing a page.
instead using css instead, will allow you to use the different classes in different parts of the code and also is not cluttering the html (as it already it).

also, there are lots of helpers already in the bootstrap framework that you can use, take advantage of those.

in this particular example of the table that you created, if you move them to be header, they are most likely already bolded by default styling of bootstrap.

**Comment by SLMassari** [comment]
Didn't realize I just needed to use <thead></thead> to do what I wanted
