### ISSUE TITLE
assign the id to the row not the data

### ISSUE THREAD

**Issue by niesmo** [niesmo/childcare#40]
assigning the id of the action item to the data (td), would make it harder for you to get the id of the action item when they click on the row.

but the point of an id is something that is unique within a page (what is unique). we are really talking about that whole row being a unique entity not only that data part of the row.

**Comment by SLMassari** [comment]
I originally had that when changing it to clicking the row. I've changed it now, but it still seems to only work when clicking the description. I'll push that change
