### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by niesmo** [niesmo/childcare#50]
We need to create the presentation for Thursday.

I am suggesting to use a theme. I added the theme for our first checkpoint but was not able to move the presentation to the new Themed slides.

I am suggesting to use the following theme 
https://drive.google.com/open?id=1DmzOpW2zjN4oXPSKyZDotbuUmFrZt9_Xf5QQxkMZTpw

**Comment by SLMassari** [comment]
Presentation was created and went well
